activation: ReLU
data: /net/vast-storage/scratch/vast/tegmark/ericjm/neural-verification/tasks/rnn_prev1_numerical/data.pt
dtype: float32
hidden_dim: 2
hidden_mlp_depth: 1
hidden_mlp_width: 1
ignore_first_n_elements: 0
input_dim: 1
loss_fn: log
lr: 0.001
max_hidden_dim: 128
max_hidden_mlp_depth: 3
max_hidden_mlp_width: 256
max_output_mlp_depth: 3
max_output_mlp_width: 256
output_dim: 1
output_mlp_depth: 1
output_mlp_width: 1
progress_bar: false
save_dir: /net/vast-storage/scratch/vast/tegmark/ericjm/neural-verification/archtest0/1702877699/rnn_prev1_numerical/runs/65536_0
seed: 0
seeds_per_run: 5
steps: 10000
test_batch_size: 65536
train_batch_size: 4096
vectorize_input: false
weight_decay: 0.0
